const currentEjem = {
  last_updated_epoch: 1705188600,
  last_updated: '2024-01-13 23:30',
  temp_c: 3.0,
  temp_f: 37.4,
  is_day: 0,
  condition: {
    text: 'Overcast',
    icon: '//cdn.weatherapi.com/weather/64x64/night/122.png',
    code: 1009
  },
  wind_mph: 6.9,
  wind_kph: 11.2,
  wind_degree: 210,
  wind_dir: 'SSW',
  pressure_mb: 1019.0,
  pressure_in: 30.09,
  precip_mm: 0.0,
  precip_in: 0.0,
  humidity: 87,
  cloud: 100,
  feelslike_c: 1.1,
  feelslike_f: 34.1,
  vis_km: 10.0,
  vis_miles: 6.0,
  uv: 1.0,
  gust_mph: 7.9,
  gust_kph: 12.7
}
const locationEjem = {
  name: 'London',
  region: 'City of London, Greater London',
  country: 'United Kingdom',
  lat: 51.52,
  lon: -0.11,
  tz_id: 'Europe/London',
  localtime_epoch: 1705189435,
  localtime: '2024-01-13 23:43'
}
const forecastEjem = {
  forecastday: [
    {
      date: '2024-01-13',
      date_epoch: 1705104000,
      day: {
        maxtemp_c: 4.2,
        maxtemp_f: 39.6,
        mintemp_c: 0.8,
        mintemp_f: 33.4,
        avgtemp_c: 2.3,
        avgtemp_f: 36.1,
        maxwind_mph: 6.5,
        maxwind_kph: 10.4,
        totalprecip_mm: 0.0,
        totalprecip_in: 0.0,
        totalsnow_cm: 0.0,
        avgvis_km: 8.3,
        avgvis_miles: 5.0,
        avghumidity: 88,
        daily_will_it_rain: 0,
        daily_chance_of_rain: 0,
        daily_will_it_snow: 0,
        daily_chance_of_snow: 0,
        condition: {
          text: 'Partly cloudy',
          icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
          code: 1003
        },
        uv: 1.0
      },
      astro: {
        sunrise: '08:01 AM',
        sunset: '04:17 PM',
        moonrise: '09:48 AM',
        moonset: '06:50 PM',
        moon_phase: 'Waxing Crescent',
        moon_illumination: 3,
        is_moon_up: 0,
        is_sun_up: 0
      },
      hour: [
        {
          time_epoch: 1705104000,
          time: '2024-01-13 00:00',
          temp_c: 2.8,
          temp_f: 37.1,
          is_day: 0,
          condition: {
            text: 'Clear',
            icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
            code: 1000
          },
          wind_mph: 3.8,
          wind_kph: 6.1,
          wind_degree: 262,
          wind_dir: 'W',
          pressure_mb: 1031.0,
          pressure_in: 30.46,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 84,
          cloud: 2,
          feelslike_c: 1.2,
          feelslike_f: 34.2,
          windchill_c: 1.2,
          windchill_f: 34.2,
          heatindex_c: 2.9,
          heatindex_f: 37.1,
          dewpoint_c: 0.4,
          dewpoint_f: 32.7,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 6.3,
          gust_kph: 10.1,
          uv: 1.0
        },
        {
          time_epoch: 1705107600,
          time: '2024-01-13 01:00',
          temp_c: 2.4,
          temp_f: 36.4,
          is_day: 0,
          condition: {
            text: 'Clear',
            icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
            code: 1000
          },
          wind_mph: 4.3,
          wind_kph: 6.8,
          wind_degree: 270,
          wind_dir: 'W',
          pressure_mb: 1031.0,
          pressure_in: 30.44,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 86,
          cloud: 9,
          feelslike_c: 0.5,
          feelslike_f: 32.9,
          windchill_c: 0.5,
          windchill_f: 32.9,
          heatindex_c: 2.4,
          heatindex_f: 36.4,
          dewpoint_c: 0.4,
          dewpoint_f: 32.7,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 7.0,
          gust_kph: 11.2,
          uv: 1.0
        },
        {
          time_epoch: 1705111200,
          time: '2024-01-13 02:00',
          temp_c: 2.1,
          temp_f: 35.7,
          is_day: 0,
          condition: {
            text: 'Clear',
            icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
            code: 1000
          },
          wind_mph: 4.3,
          wind_kph: 6.8,
          wind_degree: 278,
          wind_dir: 'W',
          pressure_mb: 1031.0,
          pressure_in: 30.43,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 89,
          cloud: 19,
          feelslike_c: 0.0,
          feelslike_f: 32.1,
          windchill_c: 0.0,
          windchill_f: 32.1,
          heatindex_c: 2.1,
          heatindex_f: 35.7,
          dewpoint_c: 0.4,
          dewpoint_f: 32.7,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 6.8,
          gust_kph: 11.0,
          uv: 1.0
        },
        {
          time_epoch: 1705114800,
          time: '2024-01-13 03:00',
          temp_c: 1.9,
          temp_f: 35.4,
          is_day: 0,
          condition: {
            text: 'Partly cloudy',
            icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
            code: 1003
          },
          wind_mph: 4.7,
          wind_kph: 7.6,
          wind_degree: 264,
          wind_dir: 'W',
          pressure_mb: 1030.0,
          pressure_in: 30.41,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 91,
          cloud: 43,
          feelslike_c: -0.4,
          feelslike_f: 31.3,
          windchill_c: -0.4,
          windchill_f: 31.3,
          heatindex_c: 1.9,
          heatindex_f: 35.4,
          dewpoint_c: 0.7,
          dewpoint_f: 33.2,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 7.4,
          gust_kph: 11.8,
          uv: 1.0
        },
        {
          time_epoch: 1705118400,
          time: '2024-01-13 04:00',
          temp_c: 1.6,
          temp_f: 34.8,
          is_day: 0,
          condition: {
            text: 'Partly cloudy',
            icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
            code: 1003
          },
          wind_mph: 4.9,
          wind_kph: 7.9,
          wind_degree: 262,
          wind_dir: 'W',
          pressure_mb: 1029.0,
          pressure_in: 30.39,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 93,
          cloud: 55,
          feelslike_c: -0.9,
          feelslike_f: 30.4,
          windchill_c: -0.9,
          windchill_f: 30.4,
          heatindex_c: 1.6,
          heatindex_f: 34.8,
          dewpoint_c: 0.6,
          dewpoint_f: 33.1,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 7.7,
          gust_kph: 12.5,
          uv: 1.0
        },
        {
          time_epoch: 1705122000,
          time: '2024-01-13 05:00',
          temp_c: 1.3,
          temp_f: 34.3,
          is_day: 0,
          condition: {
            text: 'Mist',
            icon: '//cdn.weatherapi.com/weather/64x64/night/143.png',
            code: 1030
          },
          wind_mph: 5.4,
          wind_kph: 8.6,
          wind_degree: 259,
          wind_dir: 'W',
          pressure_mb: 1028.0,
          pressure_in: 30.36,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 95,
          cloud: 65,
          feelslike_c: -1.4,
          feelslike_f: 29.4,
          windchill_c: -1.4,
          windchill_f: 29.4,
          heatindex_c: 1.3,
          heatindex_f: 34.3,
          dewpoint_c: 0.5,
          dewpoint_f: 32.9,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 2.0,
          vis_miles: 1.0,
          gust_mph: 8.4,
          gust_kph: 13.6,
          uv: 1.0
        },
        {
          time_epoch: 1705125600,
          time: '2024-01-13 06:00',
          temp_c: 1.0,
          temp_f: 33.8,
          is_day: 0,
          condition: {
            text: 'Mist',
            icon: '//cdn.weatherapi.com/weather/64x64/night/143.png',
            code: 1030
          },
          wind_mph: 5.8,
          wind_kph: 9.4,
          wind_degree: 307,
          wind_dir: 'NW',
          pressure_mb: 1029.0,
          pressure_in: 30.37,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 95,
          cloud: 83,
          feelslike_c: -2.0,
          feelslike_f: 28.5,
          windchill_c: -2.0,
          windchill_f: 28.5,
          heatindex_c: 1.0,
          heatindex_f: 33.8,
          dewpoint_c: 0.3,
          dewpoint_f: 32.5,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 2.0,
          vis_miles: 1.0,
          gust_mph: 8.7,
          gust_kph: 14.0,
          uv: 1.0
        },
        {
          time_epoch: 1705129200,
          time: '2024-01-13 07:00',
          temp_c: 0.8,
          temp_f: 33.4,
          is_day: 0,
          condition: {
            text: 'Cloudy',
            icon: '//cdn.weatherapi.com/weather/64x64/night/119.png',
            code: 1006
          },
          wind_mph: 5.6,
          wind_kph: 9.0,
          wind_degree: 295,
          wind_dir: 'WNW',
          pressure_mb: 1028.0,
          pressure_in: 30.35,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 94,
          cloud: 81,
          feelslike_c: -2.1,
          feelslike_f: 28.2,
          windchill_c: -2.1,
          windchill_f: 28.2,
          heatindex_c: 0.8,
          heatindex_f: 33.4,
          dewpoint_c: -0.1,
          dewpoint_f: 31.7,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 8.0,
          gust_kph: 12.9,
          uv: 1.0
        },
        {
          time_epoch: 1705132800,
          time: '2024-01-13 08:00',
          temp_c: 0.8,
          temp_f: 33.5,
          is_day: 0,
          condition: {
            text: 'Cloudy',
            icon: '//cdn.weatherapi.com/weather/64x64/night/119.png',
            code: 1006
          },
          wind_mph: 6.5,
          wind_kph: 10.4,
          wind_degree: 300,
          wind_dir: 'WNW',
          pressure_mb: 1027.0,
          pressure_in: 30.34,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 91,
          cloud: 70,
          feelslike_c: -2.4,
          feelslike_f: 27.7,
          windchill_c: -2.4,
          windchill_f: 27.7,
          heatindex_c: 0.9,
          heatindex_f: 33.5,
          dewpoint_c: -0.5,
          dewpoint_f: 31.2,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 9.1,
          gust_kph: 14.6,
          uv: 1.0
        },
        {
          time_epoch: 1705136400,
          time: '2024-01-13 09:00',
          temp_c: 1.4,
          temp_f: 34.5,
          is_day: 1,
          condition: {
            text: 'Partly cloudy',
            icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
            code: 1003
          },
          wind_mph: 6.3,
          wind_kph: 10.1,
          wind_degree: 302,
          wind_dir: 'WNW',
          pressure_mb: 1027.0,
          pressure_in: 30.32,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 87,
          cloud: 46,
          feelslike_c: -1.7,
          feelslike_f: 28.9,
          windchill_c: -1.7,
          windchill_f: 28.9,
          heatindex_c: 1.4,
          heatindex_f: 34.4,
          dewpoint_c: -0.6,
          dewpoint_f: 30.9,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 8.4,
          gust_kph: 13.6,
          uv: 2.0
        },
        {
          time_epoch: 1705140000,
          time: '2024-01-13 10:00',
          temp_c: 1.9,
          temp_f: 35.5,
          is_day: 1,
          condition: {
            text: 'Partly cloudy',
            icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
            code: 1003
          },
          wind_mph: 5.8,
          wind_kph: 9.4,
          wind_degree: 302,
          wind_dir: 'WNW',
          pressure_mb: 1027.0,
          pressure_in: 30.32,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 84,
          cloud: 30,
          feelslike_c: -0.8,
          feelslike_f: 30.5,
          windchill_c: -0.8,
          windchill_f: 30.5,
          heatindex_c: 1.9,
          heatindex_f: 35.5,
          dewpoint_c: -0.5,
          dewpoint_f: 31.0,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 7.7,
          gust_kph: 12.3,
          uv: 2.0
        },
        {
          time_epoch: 1705143600,
          time: '2024-01-13 11:00',
          temp_c: 2.6,
          temp_f: 36.7,
          is_day: 1,
          condition: {
            text: 'Sunny',
            icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
            code: 1000
          },
          wind_mph: 5.4,
          wind_kph: 8.6,
          wind_degree: 300,
          wind_dir: 'WNW',
          pressure_mb: 1026.0,
          pressure_in: 30.31,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 81,
          cloud: 21,
          feelslike_c: 0.2,
          feelslike_f: 32.3,
          windchill_c: 0.2,
          windchill_f: 32.3,
          heatindex_c: 2.6,
          heatindex_f: 36.7,
          dewpoint_c: -0.2,
          dewpoint_f: 31.6,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 6.9,
          gust_kph: 11.2,
          uv: 2.0
        },
        {
          time_epoch: 1705147200,
          time: '2024-01-13 12:00',
          temp_c: 3.2,
          temp_f: 37.8,
          is_day: 1,
          condition: {
            text: 'Sunny',
            icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
            code: 1000
          },
          wind_mph: 5.4,
          wind_kph: 8.6,
          wind_degree: 285,
          wind_dir: 'WNW',
          pressure_mb: 1025.0,
          pressure_in: 30.28,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 80,
          cloud: 14,
          feelslike_c: 0.9,
          feelslike_f: 33.5,
          windchill_c: 0.9,
          windchill_f: 33.5,
          heatindex_c: 3.2,
          heatindex_f: 37.8,
          dewpoint_c: 0.1,
          dewpoint_f: 32.2,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 6.9,
          gust_kph: 11.1,
          uv: 2.0
        },
        {
          time_epoch: 1705150800,
          time: '2024-01-13 13:00',
          temp_c: 3.8,
          temp_f: 38.9,
          is_day: 1,
          condition: {
            text: 'Sunny',
            icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
            code: 1000
          },
          wind_mph: 5.8,
          wind_kph: 9.4,
          wind_degree: 277,
          wind_dir: 'W',
          pressure_mb: 1024.0,
          pressure_in: 30.25,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 78,
          cloud: 11,
          feelslike_c: 1.4,
          feelslike_f: 34.5,
          windchill_c: 1.4,
          windchill_f: 34.5,
          heatindex_c: 3.8,
          heatindex_f: 38.9,
          dewpoint_c: 0.4,
          dewpoint_f: 32.7,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 7.4,
          gust_kph: 12.0,
          uv: 2.0
        },
        {
          time_epoch: 1705154400,
          time: '2024-01-13 14:00',
          temp_c: 4.2,
          temp_f: 39.6,
          is_day: 1,
          condition: {
            text: 'Sunny',
            icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
            code: 1000
          },
          wind_mph: 6.3,
          wind_kph: 10.1,
          wind_degree: 268,
          wind_dir: 'W',
          pressure_mb: 1023.0,
          pressure_in: 30.22,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 77,
          cloud: 5,
          feelslike_c: 1.7,
          feelslike_f: 35.0,
          windchill_c: 1.7,
          windchill_f: 35.0,
          heatindex_c: 4.2,
          heatindex_f: 39.6,
          dewpoint_c: 0.6,
          dewpoint_f: 33.0,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 8.2,
          gust_kph: 13.2,
          uv: 2.0
        },
        {
          time_epoch: 1705158000,
          time: '2024-01-13 15:00',
          temp_c: 4.2,
          temp_f: 39.6,
          is_day: 1,
          condition: {
            text: 'Sunny',
            icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
            code: 1000
          },
          wind_mph: 5.4,
          wind_kph: 8.6,
          wind_degree: 269,
          wind_dir: 'W',
          pressure_mb: 1023.0,
          pressure_in: 30.2,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 78,
          cloud: 2,
          feelslike_c: 2.0,
          feelslike_f: 35.7,
          windchill_c: 2.0,
          windchill_f: 35.7,
          heatindex_c: 4.2,
          heatindex_f: 39.6,
          dewpoint_c: 0.8,
          dewpoint_f: 33.4,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 7.4,
          gust_kph: 11.9,
          uv: 2.0
        },
        {
          time_epoch: 1705161600,
          time: '2024-01-13 16:00',
          temp_c: 3.5,
          temp_f: 38.2,
          is_day: 1,
          condition: {
            text: 'Sunny',
            icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
            code: 1000
          },
          wind_mph: 4.5,
          wind_kph: 7.2,
          wind_degree: 248,
          wind_dir: 'WSW',
          pressure_mb: 1022.0,
          pressure_in: 30.19,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 83,
          cloud: 6,
          feelslike_c: 1.6,
          feelslike_f: 34.8,
          windchill_c: 1.6,
          windchill_f: 34.8,
          heatindex_c: 3.5,
          heatindex_f: 38.2,
          dewpoint_c: 0.8,
          dewpoint_f: 33.5,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 7.0,
          gust_kph: 11.2,
          uv: 2.0
        },
        {
          time_epoch: 1705165200,
          time: '2024-01-13 17:00',
          temp_c: 2.8,
          temp_f: 37.1,
          is_day: 0,
          condition: {
            text: 'Clear',
            icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
            code: 1000
          },
          wind_mph: 4.5,
          wind_kph: 7.2,
          wind_degree: 247,
          wind_dir: 'WSW',
          pressure_mb: 1022.0,
          pressure_in: 30.18,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 86,
          cloud: 24,
          feelslike_c: 0.8,
          feelslike_f: 33.5,
          windchill_c: 0.8,
          windchill_f: 33.5,
          heatindex_c: 2.8,
          heatindex_f: 37.1,
          dewpoint_c: 0.8,
          dewpoint_f: 33.5,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 7.4,
          gust_kph: 12.0,
          uv: 1.0
        },
        {
          time_epoch: 1705168800,
          time: '2024-01-13 18:00',
          temp_c: 2.5,
          temp_f: 36.6,
          is_day: 0,
          condition: {
            text: 'Partly cloudy',
            icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
            code: 1003
          },
          wind_mph: 4.3,
          wind_kph: 6.8,
          wind_degree: 257,
          wind_dir: 'WSW',
          pressure_mb: 1022.0,
          pressure_in: 30.17,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 89,
          cloud: 43,
          feelslike_c: 0.6,
          feelslike_f: 33.1,
          windchill_c: 0.6,
          windchill_f: 33.1,
          heatindex_c: 2.5,
          heatindex_f: 36.6,
          dewpoint_c: 0.9,
          dewpoint_f: 33.6,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 7.2,
          gust_kph: 11.6,
          uv: 1.0
        },
        {
          time_epoch: 1705172400,
          time: '2024-01-13 19:00',
          temp_c: 2.3,
          temp_f: 36.2,
          is_day: 0,
          condition: {
            text: 'Partly cloudy',
            icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
            code: 1003
          },
          wind_mph: 4.0,
          wind_kph: 6.5,
          wind_degree: 264,
          wind_dir: 'W',
          pressure_mb: 1021.0,
          pressure_in: 30.15,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 91,
          cloud: 34,
          feelslike_c: 0.5,
          feelslike_f: 32.8,
          windchill_c: 0.5,
          windchill_f: 32.8,
          heatindex_c: 2.3,
          heatindex_f: 36.2,
          dewpoint_c: 1.0,
          dewpoint_f: 33.8,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 7.0,
          gust_kph: 11.3,
          uv: 1.0
        },
        {
          time_epoch: 1705176000,
          time: '2024-01-13 20:00',
          temp_c: 2.2,
          temp_f: 35.9,
          is_day: 0,
          condition: {
            text: 'Partly cloudy',
            icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
            code: 1003
          },
          wind_mph: 3.6,
          wind_kph: 5.8,
          wind_degree: 270,
          wind_dir: 'W',
          pressure_mb: 1021.0,
          pressure_in: 30.15,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 93,
          cloud: 49,
          feelslike_c: 0.6,
          feelslike_f: 33.0,
          windchill_c: 0.6,
          windchill_f: 33.0,
          heatindex_c: 2.2,
          heatindex_f: 35.9,
          dewpoint_c: 1.2,
          dewpoint_f: 34.1,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 6.4,
          gust_kph: 10.4,
          uv: 1.0
        },
        {
          time_epoch: 1705179600,
          time: '2024-01-13 21:00',
          temp_c: 2.1,
          temp_f: 35.7,
          is_day: 0,
          condition: {
            text: 'Mist',
            icon: '//cdn.weatherapi.com/weather/64x64/night/143.png',
            code: 1030
          },
          wind_mph: 4.0,
          wind_kph: 6.5,
          wind_degree: 261,
          wind_dir: 'W',
          pressure_mb: 1021.0,
          pressure_in: 30.14,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 95,
          cloud: 62,
          feelslike_c: 0.2,
          feelslike_f: 32.3,
          windchill_c: 0.2,
          windchill_f: 32.3,
          heatindex_c: 2.1,
          heatindex_f: 35.7,
          dewpoint_c: 1.3,
          dewpoint_f: 34.3,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 2.0,
          vis_miles: 1.0,
          gust_mph: 7.3,
          gust_kph: 11.8,
          uv: 1.0
        },
        {
          time_epoch: 1705183200,
          time: '2024-01-13 22:00',
          temp_c: 1.9,
          temp_f: 35.4,
          is_day: 0,
          condition: {
            text: 'Mist',
            icon: '//cdn.weatherapi.com/weather/64x64/night/143.png',
            code: 1030
          },
          wind_mph: 4.0,
          wind_kph: 6.5,
          wind_degree: 257,
          wind_dir: 'WSW',
          pressure_mb: 1021.0,
          pressure_in: 30.14,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 96,
          cloud: 49,
          feelslike_c: -0.0,
          feelslike_f: 32.0,
          windchill_c: -0.0,
          windchill_f: 32.0,
          heatindex_c: 1.9,
          heatindex_f: 35.4,
          dewpoint_c: 1.3,
          dewpoint_f: 34.4,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 2.0,
          vis_miles: 1.0,
          gust_mph: 7.3,
          gust_kph: 11.8,
          uv: 1.0
        },
        {
          time_epoch: 1705186800,
          time: '2024-01-13 23:00',
          temp_c: 3.0,
          temp_f: 37.4,
          is_day: 0,
          condition: {
            text: 'Overcast',
            icon: '//cdn.weatherapi.com/weather/64x64/night/122.png',
            code: 1009
          },
          wind_mph: 6.9,
          wind_kph: 11.2,
          wind_degree: 210,
          wind_dir: 'SSW',
          pressure_mb: 1019.0,
          pressure_in: 30.09,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 87,
          cloud: 100,
          feelslike_c: -0.3,
          feelslike_f: 31.4,
          windchill_c: -0.3,
          windchill_f: 31.4,
          heatindex_c: 1.8,
          heatindex_f: 35.2,
          dewpoint_c: 1.3,
          dewpoint_f: 34.3,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 7.9,
          gust_kph: 12.7,
          uv: 1.0
        }
      ]
    },
    {
      date: '2024-01-14',
      date_epoch: 1705190400,
      day: {
        maxtemp_c: 5.3,
        maxtemp_f: 41.6,
        mintemp_c: 1.6,
        mintemp_f: 35.0,
        avgtemp_c: 3.5,
        avgtemp_f: 38.3,
        maxwind_mph: 8.5,
        maxwind_kph: 13.7,
        totalprecip_mm: 0.42,
        totalprecip_in: 0.02,
        totalsnow_cm: 0.22,
        avgvis_km: 9.0,
        avgvis_miles: 5.0,
        avghumidity: 80,
        daily_will_it_rain: 1,
        daily_chance_of_rain: 87,
        daily_will_it_snow: 0,
        daily_chance_of_snow: 0,
        condition: {
          text: 'Patchy rain possible',
          icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
          code: 1063
        },
        uv: 1.0
      },
      astro: {
        sunrise: '08:01 AM',
        sunset: '04:18 PM',
        moonrise: '10:06 AM',
        moonset: '08:22 PM',
        moon_phase: 'Waxing Crescent',
        moon_illumination: 9,
        is_moon_up: 0,
        is_sun_up: 0
      },
      hour: [
        {
          time_epoch: 1705190400,
          time: '2024-01-14 00:00',
          temp_c: 1.6,
          temp_f: 35.0,
          is_day: 0,
          condition: {
            text: 'Mist',
            icon: '//cdn.weatherapi.com/weather/64x64/night/143.png',
            code: 1030
          },
          wind_mph: 4.0,
          wind_kph: 6.5,
          wind_degree: 258,
          wind_dir: 'WSW',
          pressure_mb: 1019.0,
          pressure_in: 30.09,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 97,
          cloud: 52,
          feelslike_c: -0.3,
          feelslike_f: 31.4,
          windchill_c: -0.3,
          windchill_f: 31.4,
          heatindex_c: 1.6,
          heatindex_f: 35.0,
          dewpoint_c: 1.2,
          dewpoint_f: 34.1,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 2.0,
          vis_miles: 1.0,
          gust_mph: 7.6,
          gust_kph: 12.2,
          uv: 1.0
        },
        {
          time_epoch: 1705194000,
          time: '2024-01-14 01:00',
          temp_c: 1.8,
          temp_f: 35.3,
          is_day: 0,
          condition: {
            text: 'Mist',
            icon: '//cdn.weatherapi.com/weather/64x64/night/143.png',
            code: 1030
          },
          wind_mph: 3.8,
          wind_kph: 6.1,
          wind_degree: 255,
          wind_dir: 'WSW',
          pressure_mb: 1018.0,
          pressure_in: 30.07,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 95,
          cloud: 92,
          feelslike_c: 0.0,
          feelslike_f: 32.1,
          windchill_c: 0.0,
          windchill_f: 32.1,
          heatindex_c: 1.8,
          heatindex_f: 35.3,
          dewpoint_c: 1.2,
          dewpoint_f: 34.1,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 2.0,
          vis_miles: 1.0,
          gust_mph: 7.2,
          gust_kph: 11.6,
          uv: 1.0
        },
        {
          time_epoch: 1705197600,
          time: '2024-01-14 02:00',
          temp_c: 2.6,
          temp_f: 36.7,
          is_day: 0,
          condition: {
            text: 'Cloudy',
            icon: '//cdn.weatherapi.com/weather/64x64/night/119.png',
            code: 1006
          },
          wind_mph: 3.6,
          wind_kph: 5.8,
          wind_degree: 251,
          wind_dir: 'WSW',
          pressure_mb: 1018.0,
          pressure_in: 30.05,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 90,
          cloud: 74,
          feelslike_c: 1.1,
          feelslike_f: 33.9,
          windchill_c: 1.1,
          windchill_f: 33.9,
          heatindex_c: 2.6,
          heatindex_f: 36.7,
          dewpoint_c: 1.2,
          dewpoint_f: 34.2,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 6.4,
          gust_kph: 10.3,
          uv: 1.0
        },
        {
          time_epoch: 1705201200,
          time: '2024-01-14 03:00',
          temp_c: 2.9,
          temp_f: 37.2,
          is_day: 0,
          condition: {
            text: 'Cloudy',
            icon: '//cdn.weatherapi.com/weather/64x64/night/119.png',
            code: 1006
          },
          wind_mph: 3.6,
          wind_kph: 5.8,
          wind_degree: 271,
          wind_dir: 'W',
          pressure_mb: 1017.0,
          pressure_in: 30.04,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 89,
          cloud: 66,
          feelslike_c: 1.4,
          feelslike_f: 34.5,
          windchill_c: 1.4,
          windchill_f: 34.5,
          heatindex_c: 2.9,
          heatindex_f: 37.2,
          dewpoint_c: 1.2,
          dewpoint_f: 34.2,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 6.2,
          gust_kph: 9.9,
          uv: 1.0
        },
        {
          time_epoch: 1705204800,
          time: '2024-01-14 04:00',
          temp_c: 3.1,
          temp_f: 37.5,
          is_day: 0,
          condition: {
            text: 'Cloudy',
            icon: '//cdn.weatherapi.com/weather/64x64/night/119.png',
            code: 1006
          },
          wind_mph: 4.0,
          wind_kph: 6.5,
          wind_degree: 291,
          wind_dir: 'WNW',
          pressure_mb: 1017.0,
          pressure_in: 30.02,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 88,
          cloud: 86,
          feelslike_c: 1.4,
          feelslike_f: 34.4,
          windchill_c: 1.4,
          windchill_f: 34.4,
          heatindex_c: 3.1,
          heatindex_f: 37.5,
          dewpoint_c: 1.4,
          dewpoint_f: 34.5,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 6.7,
          gust_kph: 10.8,
          uv: 1.0
        },
        {
          time_epoch: 1705208400,
          time: '2024-01-14 05:00',
          temp_c: 3.2,
          temp_f: 37.7,
          is_day: 0,
          condition: {
            text: 'Cloudy',
            icon: '//cdn.weatherapi.com/weather/64x64/night/119.png',
            code: 1006
          },
          wind_mph: 4.5,
          wind_kph: 7.2,
          wind_degree: 299,
          wind_dir: 'WNW',
          pressure_mb: 1016.0,
          pressure_in: 30.0,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 87,
          cloud: 80,
          feelslike_c: 1.2,
          feelslike_f: 34.2,
          windchill_c: 1.2,
          windchill_f: 34.2,
          heatindex_c: 3.2,
          heatindex_f: 37.7,
          dewpoint_c: 1.3,
          dewpoint_f: 34.3,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 7.3,
          gust_kph: 11.7,
          uv: 1.0
        },
        {
          time_epoch: 1705212000,
          time: '2024-01-14 06:00',
          temp_c: 3.1,
          temp_f: 37.6,
          is_day: 0,
          condition: {
            text: 'Overcast',
            icon: '//cdn.weatherapi.com/weather/64x64/night/122.png',
            code: 1009
          },
          wind_mph: 4.3,
          wind_kph: 6.8,
          wind_degree: 299,
          wind_dir: 'WNW',
          pressure_mb: 1016.0,
          pressure_in: 29.99,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 84,
          cloud: 91,
          feelslike_c: 1.3,
          feelslike_f: 34.3,
          windchill_c: 1.3,
          windchill_f: 34.3,
          heatindex_c: 3.1,
          heatindex_f: 37.7,
          dewpoint_c: 0.6,
          dewpoint_f: 33.1,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 6.9,
          gust_kph: 11.1,
          uv: 1.0
        },
        {
          time_epoch: 1705215600,
          time: '2024-01-14 07:00',
          temp_c: 3.0,
          temp_f: 37.5,
          is_day: 0,
          condition: {
            text: 'Overcast',
            icon: '//cdn.weatherapi.com/weather/64x64/night/122.png',
            code: 1009
          },
          wind_mph: 3.8,
          wind_kph: 6.1,
          wind_degree: 281,
          wind_dir: 'WNW',
          pressure_mb: 1015.0,
          pressure_in: 29.99,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 82,
          cloud: 92,
          feelslike_c: 1.4,
          feelslike_f: 34.6,
          windchill_c: 1.4,
          windchill_f: 34.6,
          heatindex_c: 3.0,
          heatindex_f: 37.5,
          dewpoint_c: 0.2,
          dewpoint_f: 32.4,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 6.2,
          gust_kph: 9.9,
          uv: 1.0
        },
        {
          time_epoch: 1705219200,
          time: '2024-01-14 08:00',
          temp_c: 3.0,
          temp_f: 37.4,
          is_day: 0,
          condition: {
            text: 'Overcast',
            icon: '//cdn.weatherapi.com/weather/64x64/night/122.png',
            code: 1009
          },
          wind_mph: 4.0,
          wind_kph: 6.5,
          wind_degree: 267,
          wind_dir: 'W',
          pressure_mb: 1015.0,
          pressure_in: 29.98,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 81,
          cloud: 88,
          feelslike_c: 1.3,
          feelslike_f: 34.3,
          windchill_c: 1.3,
          windchill_f: 34.3,
          heatindex_c: 3.0,
          heatindex_f: 37.4,
          dewpoint_c: 0.1,
          dewpoint_f: 32.2,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 6.6,
          gust_kph: 10.6,
          uv: 1.0
        },
        {
          time_epoch: 1705222800,
          time: '2024-01-14 09:00',
          temp_c: 3.3,
          temp_f: 37.9,
          is_day: 1,
          condition: {
            text: 'Cloudy',
            icon: '//cdn.weatherapi.com/weather/64x64/day/119.png',
            code: 1006
          },
          wind_mph: 4.7,
          wind_kph: 7.6,
          wind_degree: 264,
          wind_dir: 'W',
          pressure_mb: 1015.0,
          pressure_in: 29.97,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 79,
          cloud: 85,
          feelslike_c: 1.3,
          feelslike_f: 34.3,
          windchill_c: 1.3,
          windchill_f: 34.3,
          heatindex_c: 3.3,
          heatindex_f: 37.9,
          dewpoint_c: 0.1,
          dewpoint_f: 32.2,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 7.4,
          gust_kph: 12.0,
          uv: 1.0
        },
        {
          time_epoch: 1705226400,
          time: '2024-01-14 10:00',
          temp_c: 4.0,
          temp_f: 39.3,
          is_day: 1,
          condition: {
            text: 'Cloudy',
            icon: '//cdn.weatherapi.com/weather/64x64/day/119.png',
            code: 1006
          },
          wind_mph: 6.3,
          wind_kph: 10.1,
          wind_degree: 265,
          wind_dir: 'W',
          pressure_mb: 1015.0,
          pressure_in: 29.96,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 75,
          cloud: 83,
          feelslike_c: 1.5,
          feelslike_f: 34.7,
          windchill_c: 1.5,
          windchill_f: 34.7,
          heatindex_c: 4.1,
          heatindex_f: 39.3,
          dewpoint_c: 0.1,
          dewpoint_f: 32.1,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 9.1,
          gust_kph: 14.7,
          uv: 1.0
        },
        {
          time_epoch: 1705230000,
          time: '2024-01-14 11:00',
          temp_c: 4.9,
          temp_f: 40.8,
          is_day: 1,
          condition: {
            text: 'Partly cloudy',
            icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
            code: 1003
          },
          wind_mph: 7.6,
          wind_kph: 12.2,
          wind_degree: 287,
          wind_dir: 'WNW',
          pressure_mb: 1014.0,
          pressure_in: 29.95,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 67,
          cloud: 43,
          feelslike_c: 2.1,
          feelslike_f: 35.7,
          windchill_c: 2.1,
          windchill_f: 35.7,
          heatindex_c: 4.9,
          heatindex_f: 40.8,
          dewpoint_c: -0.7,
          dewpoint_f: 30.8,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 10.4,
          gust_kph: 16.7,
          uv: 2.0
        },
        {
          time_epoch: 1705233600,
          time: '2024-01-14 12:00',
          temp_c: 5.0,
          temp_f: 41.1,
          is_day: 1,
          condition: {
            text: 'Sunny',
            icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
            code: 1000
          },
          wind_mph: 8.5,
          wind_kph: 13.7,
          wind_degree: 313,
          wind_dir: 'NW',
          pressure_mb: 1013.0,
          pressure_in: 29.92,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 65,
          cloud: 7,
          feelslike_c: 2.0,
          feelslike_f: 35.6,
          windchill_c: 2.0,
          windchill_f: 35.6,
          heatindex_c: 5.0,
          heatindex_f: 41.1,
          dewpoint_c: -0.9,
          dewpoint_f: 30.4,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 10.9,
          gust_kph: 17.5,
          uv: 3.0
        },
        {
          time_epoch: 1705237200,
          time: '2024-01-14 13:00',
          temp_c: 5.2,
          temp_f: 41.4,
          is_day: 1,
          condition: {
            text: 'Sunny',
            icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
            code: 1000
          },
          wind_mph: 7.2,
          wind_kph: 11.5,
          wind_degree: 317,
          wind_dir: 'NW',
          pressure_mb: 1013.0,
          pressure_in: 29.9,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 64,
          cloud: 9,
          feelslike_c: 2.6,
          feelslike_f: 36.7,
          windchill_c: 2.6,
          windchill_f: 36.7,
          heatindex_c: 5.2,
          heatindex_f: 41.4,
          dewpoint_c: -0.9,
          dewpoint_f: 30.3,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 9.1,
          gust_kph: 14.7,
          uv: 3.0
        },
        {
          time_epoch: 1705240800,
          time: '2024-01-14 14:00',
          temp_c: 5.3,
          temp_f: 41.6,
          is_day: 1,
          condition: {
            text: 'Partly cloudy',
            icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
            code: 1003
          },
          wind_mph: 6.7,
          wind_kph: 10.8,
          wind_degree: 309,
          wind_dir: 'NW',
          pressure_mb: 1012.0,
          pressure_in: 29.88,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 63,
          cloud: 26,
          feelslike_c: 2.9,
          feelslike_f: 37.2,
          windchill_c: 2.9,
          windchill_f: 37.2,
          heatindex_c: 5.4,
          heatindex_f: 41.6,
          dewpoint_c: -1.0,
          dewpoint_f: 30.2,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 8.8,
          gust_kph: 14.1,
          uv: 3.0
        },
        {
          time_epoch: 1705244400,
          time: '2024-01-14 15:00',
          temp_c: 5.2,
          temp_f: 41.4,
          is_day: 1,
          condition: {
            text: 'Overcast',
            icon: '//cdn.weatherapi.com/weather/64x64/day/122.png',
            code: 1009
          },
          wind_mph: 6.0,
          wind_kph: 9.7,
          wind_degree: 298,
          wind_dir: 'WNW',
          pressure_mb: 1011.0,
          pressure_in: 29.86,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 66,
          cloud: 89,
          feelslike_c: 3.0,
          feelslike_f: 37.4,
          windchill_c: 3.0,
          windchill_f: 37.4,
          heatindex_c: 5.3,
          heatindex_f: 41.5,
          dewpoint_c: -0.6,
          dewpoint_f: 30.9,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 8.4,
          gust_kph: 13.5,
          uv: 2.0
        },
        {
          time_epoch: 1705248000,
          time: '2024-01-14 16:00',
          temp_c: 4.6,
          temp_f: 40.2,
          is_day: 1,
          condition: {
            text: 'Patchy rain possible',
            icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
            code: 1063
          },
          wind_mph: 6.0,
          wind_kph: 9.7,
          wind_degree: 293,
          wind_dir: 'WNW',
          pressure_mb: 1011.0,
          pressure_in: 29.86,
          precip_mm: 0.02,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 73,
          cloud: 100,
          feelslike_c: 2.2,
          feelslike_f: 36.0,
          windchill_c: 2.2,
          windchill_f: 36.0,
          heatindex_c: 4.6,
          heatindex_f: 40.2,
          dewpoint_c: 0.2,
          dewpoint_f: 32.3,
          will_it_rain: 0,
          chance_of_rain: 63,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 9.3,
          gust_kph: 14.9,
          uv: 1.0
        },
        {
          time_epoch: 1705251600,
          time: '2024-01-14 17:00',
          temp_c: 4.0,
          temp_f: 39.2,
          is_day: 0,
          condition: {
            text: 'Patchy rain possible',
            icon: '//cdn.weatherapi.com/weather/64x64/night/176.png',
            code: 1063
          },
          wind_mph: 6.9,
          wind_kph: 11.2,
          wind_degree: 294,
          wind_dir: 'WNW',
          pressure_mb: 1011.0,
          pressure_in: 29.85,
          precip_mm: 0.03,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 87,
          cloud: 100,
          feelslike_c: 1.2,
          feelslike_f: 34.1,
          windchill_c: 1.2,
          windchill_f: 34.1,
          heatindex_c: 4.0,
          heatindex_f: 39.2,
          dewpoint_c: 2.1,
          dewpoint_f: 35.7,
          will_it_rain: 0,
          chance_of_rain: 65,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 9.7,
          gust_kph: 15.6,
          uv: 1.0
        },
        {
          time_epoch: 1705255200,
          time: '2024-01-14 18:00',
          temp_c: 4.1,
          temp_f: 39.4,
          is_day: 0,
          condition: {
            text: 'Patchy rain possible',
            icon: '//cdn.weatherapi.com/weather/64x64/night/176.png',
            code: 1063
          },
          wind_mph: 6.9,
          wind_kph: 11.2,
          wind_degree: 297,
          wind_dir: 'WNW',
          pressure_mb: 1011.0,
          pressure_in: 29.84,
          precip_mm: 0.08,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 86,
          cloud: 100,
          feelslike_c: 1.3,
          feelslike_f: 34.4,
          windchill_c: 1.3,
          windchill_f: 34.4,
          heatindex_c: 4.1,
          heatindex_f: 39.4,
          dewpoint_c: 2.0,
          dewpoint_f: 35.7,
          will_it_rain: 1,
          chance_of_rain: 100,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 9.6,
          gust_kph: 15.4,
          uv: 1.0
        },
        {
          time_epoch: 1705258800,
          time: '2024-01-14 19:00',
          temp_c: 4.2,
          temp_f: 39.5,
          is_day: 0,
          condition: {
            text: 'Patchy rain possible',
            icon: '//cdn.weatherapi.com/weather/64x64/night/176.png',
            code: 1063
          },
          wind_mph: 7.8,
          wind_kph: 12.6,
          wind_degree: 306,
          wind_dir: 'NW',
          pressure_mb: 1011.0,
          pressure_in: 29.85,
          precip_mm: 0.03,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 79,
          cloud: 100,
          feelslike_c: 1.2,
          feelslike_f: 34.1,
          windchill_c: 1.2,
          windchill_f: 34.1,
          heatindex_c: 4.2,
          heatindex_f: 39.5,
          dewpoint_c: 0.8,
          dewpoint_f: 33.5,
          will_it_rain: 1,
          chance_of_rain: 87,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 10.9,
          gust_kph: 17.5,
          uv: 1.0
        },
        {
          time_epoch: 1705262400,
          time: '2024-01-14 20:00',
          temp_c: 3.5,
          temp_f: 38.2,
          is_day: 0,
          condition: {
            text: 'Moderate snow',
            icon: '//cdn.weatherapi.com/weather/64x64/night/332.png',
            code: 1219
          },
          wind_mph: 7.6,
          wind_kph: 12.2,
          wind_degree: 315,
          wind_dir: 'NW',
          pressure_mb: 1011.0,
          pressure_in: 29.85,
          precip_mm: 0.13,
          precip_in: 0.01,
          snow_cm: 0.0,
          humidity: 85,
          cloud: 100,
          feelslike_c: 0.4,
          feelslike_f: 32.6,
          windchill_c: 0.4,
          windchill_f: 32.6,
          heatindex_c: 3.5,
          heatindex_f: 38.2,
          dewpoint_c: 1.1,
          dewpoint_f: 34.1,
          will_it_rain: 1,
          chance_of_rain: 100,
          will_it_snow: 1,
          chance_of_snow: 100,
          vis_km: 5.0,
          vis_miles: 3.0,
          gust_mph: 10.4,
          gust_kph: 16.7,
          uv: 1.0
        },
        {
          time_epoch: 1705266000,
          time: '2024-01-14 21:00',
          temp_c: 2.6,
          temp_f: 36.6,
          is_day: 0,
          condition: {
            text: 'Moderate or heavy snow showers',
            icon: '//cdn.weatherapi.com/weather/64x64/night/371.png',
            code: 1258
          },
          wind_mph: 8.3,
          wind_kph: 13.3,
          wind_degree: 347,
          wind_dir: 'NNW',
          pressure_mb: 1011.0,
          pressure_in: 29.85,
          precip_mm: 0.12,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 92,
          cloud: 100,
          feelslike_c: -1.0,
          feelslike_f: 30.3,
          windchill_c: -1.0,
          windchill_f: 30.3,
          heatindex_c: 2.6,
          heatindex_f: 36.6,
          dewpoint_c: 1.4,
          dewpoint_f: 34.5,
          will_it_rain: 1,
          chance_of_rain: 100,
          will_it_snow: 1,
          chance_of_snow: 100,
          vis_km: 7.0,
          vis_miles: 4.0,
          gust_mph: 11.2,
          gust_kph: 18.1,
          uv: 1.0
        },
        {
          time_epoch: 1705269600,
          time: '2024-01-14 22:00',
          temp_c: 2.0,
          temp_f: 35.6,
          is_day: 0,
          condition: {
            text: 'Clear',
            icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
            code: 1000
          },
          wind_mph: 6.3,
          wind_kph: 10.1,
          wind_degree: 340,
          wind_dir: 'NNW',
          pressure_mb: 1011.0,
          pressure_in: 29.86,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 70,
          cloud: 22,
          feelslike_c: -0.9,
          feelslike_f: 30.3,
          windchill_c: -0.9,
          windchill_f: 30.3,
          heatindex_c: 2.0,
          heatindex_f: 35.6,
          dewpoint_c: -2.9,
          dewpoint_f: 26.8,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 8.6,
          gust_kph: 13.9,
          uv: 1.0
        },
        {
          time_epoch: 1705273200,
          time: '2024-01-14 23:00',
          temp_c: 1.9,
          temp_f: 35.3,
          is_day: 0,
          condition: {
            text: 'Clear',
            icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
            code: 1000
          },
          wind_mph: 6.7,
          wind_kph: 10.8,
          wind_degree: 332,
          wind_dir: 'NNW',
          pressure_mb: 1011.0,
          pressure_in: 29.85,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 69,
          cloud: 10,
          feelslike_c: -1.3,
          feelslike_f: 29.7,
          windchill_c: -1.3,
          windchill_f: 29.7,
          heatindex_c: 1.9,
          heatindex_f: 35.3,
          dewpoint_c: -3.2,
          dewpoint_f: 26.3,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 9.8,
          gust_kph: 15.7,
          uv: 1.0
        }
      ]
    },
    {
      date: '2024-01-15',
      date_epoch: 1705276800,
      day: {
        maxtemp_c: 2.2,
        maxtemp_f: 36.0,
        mintemp_c: -0.4,
        mintemp_f: 31.2,
        avgtemp_c: 0.6,
        avgtemp_f: 33.0,
        maxwind_mph: 11.0,
        maxwind_kph: 17.6,
        totalprecip_mm: 0.0,
        totalprecip_in: 0.0,
        totalsnow_cm: 0.0,
        avgvis_km: 10.0,
        avgvis_miles: 6.0,
        avghumidity: 59,
        daily_will_it_rain: 0,
        daily_chance_of_rain: 0,
        daily_will_it_snow: 0,
        daily_chance_of_snow: 0,
        condition: {
          text: 'Sunny',
          icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
          code: 1000
        },
        uv: 1.0
      },
      astro: {
        sunrise: '08:00 AM',
        sunset: '04:20 PM',
        moonrise: '10:21 AM',
        moonset: '09:50 PM',
        moon_phase: 'Waxing Crescent',
        moon_illumination: 17,
        is_moon_up: 0,
        is_sun_up: 0
      },
      hour: [
        {
          time_epoch: 1705276800,
          time: '2024-01-15 00:00',
          temp_c: 1.4,
          temp_f: 34.6,
          is_day: 0,
          condition: {
            text: 'Clear',
            icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
            code: 1000
          },
          wind_mph: 5.6,
          wind_kph: 9.0,
          wind_degree: 320,
          wind_dir: 'NW',
          pressure_mb: 1011.0,
          pressure_in: 29.84,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 72,
          cloud: 3,
          feelslike_c: -1.4,
          feelslike_f: 29.6,
          windchill_c: -1.4,
          windchill_f: 29.6,
          heatindex_c: 1.4,
          heatindex_f: 34.6,
          dewpoint_c: -3.1,
          dewpoint_f: 26.5,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 8.4,
          gust_kph: 13.5,
          uv: 1.0
        },
        {
          time_epoch: 1705280400,
          time: '2024-01-15 01:00',
          temp_c: 1.1,
          temp_f: 34.0,
          is_day: 0,
          condition: {
            text: 'Clear',
            icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
            code: 1000
          },
          wind_mph: 6.0,
          wind_kph: 9.7,
          wind_degree: 309,
          wind_dir: 'NW',
          pressure_mb: 1010.0,
          pressure_in: 29.83,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 78,
          cloud: 4,
          feelslike_c: -1.9,
          feelslike_f: 28.6,
          windchill_c: -1.9,
          windchill_f: 28.6,
          heatindex_c: 1.1,
          heatindex_f: 34.0,
          dewpoint_c: -2.2,
          dewpoint_f: 28.0,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 8.9,
          gust_kph: 14.4,
          uv: 1.0
        },
        {
          time_epoch: 1705284000,
          time: '2024-01-15 02:00',
          temp_c: 0.8,
          temp_f: 33.5,
          is_day: 0,
          condition: {
            text: 'Clear',
            icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
            code: 1000
          },
          wind_mph: 6.0,
          wind_kph: 9.7,
          wind_degree: 317,
          wind_dir: 'NW',
          pressure_mb: 1010.0,
          pressure_in: 29.83,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 78,
          cloud: 7,
          feelslike_c: -2.2,
          feelslike_f: 28.0,
          windchill_c: -2.2,
          windchill_f: 28.0,
          heatindex_c: 0.8,
          heatindex_f: 33.5,
          dewpoint_c: -2.5,
          dewpoint_f: 27.5,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 8.9,
          gust_kph: 14.4,
          uv: 1.0
        },
        {
          time_epoch: 1705287600,
          time: '2024-01-15 03:00',
          temp_c: 0.5,
          temp_f: 32.9,
          is_day: 0,
          condition: {
            text: 'Clear',
            icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
            code: 1000
          },
          wind_mph: 6.0,
          wind_kph: 9.7,
          wind_degree: 315,
          wind_dir: 'NW',
          pressure_mb: 1010.0,
          pressure_in: 29.83,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 73,
          cloud: 17,
          feelslike_c: -2.6,
          feelslike_f: 27.2,
          windchill_c: -2.6,
          windchill_f: 27.2,
          heatindex_c: 0.5,
          heatindex_f: 32.9,
          dewpoint_c: -3.7,
          dewpoint_f: 25.3,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 8.9,
          gust_kph: 14.4,
          uv: 1.0
        },
        {
          time_epoch: 1705291200,
          time: '2024-01-15 04:00',
          temp_c: 0.2,
          temp_f: 32.3,
          is_day: 0,
          condition: {
            text: 'Clear',
            icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
            code: 1000
          },
          wind_mph: 6.0,
          wind_kph: 9.7,
          wind_degree: 308,
          wind_dir: 'NW',
          pressure_mb: 1010.0,
          pressure_in: 29.83,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 70,
          cloud: 12,
          feelslike_c: -3.0,
          feelslike_f: 26.6,
          windchill_c: -3.0,
          windchill_f: 26.6,
          heatindex_c: 0.2,
          heatindex_f: 32.3,
          dewpoint_c: -4.5,
          dewpoint_f: 23.8,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 9.0,
          gust_kph: 14.4,
          uv: 1.0
        },
        {
          time_epoch: 1705294800,
          time: '2024-01-15 05:00',
          temp_c: 0.0,
          temp_f: 32.1,
          is_day: 0,
          condition: {
            text: 'Clear',
            icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
            code: 1000
          },
          wind_mph: 6.7,
          wind_kph: 10.8,
          wind_degree: 308,
          wind_dir: 'NW',
          pressure_mb: 1010.0,
          pressure_in: 29.82,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 70,
          cloud: 8,
          feelslike_c: -3.5,
          feelslike_f: 25.7,
          windchill_c: -3.5,
          windchill_f: 25.7,
          heatindex_c: 0.0,
          heatindex_f: 32.1,
          dewpoint_c: -4.8,
          dewpoint_f: 23.5,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 10.0,
          gust_kph: 16.1,
          uv: 1.0
        },
        {
          time_epoch: 1705298400,
          time: '2024-01-15 06:00',
          temp_c: -0.1,
          temp_f: 31.9,
          is_day: 0,
          condition: {
            text: 'Clear',
            icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
            code: 1000
          },
          wind_mph: 7.4,
          wind_kph: 11.9,
          wind_degree: 309,
          wind_dir: 'NW',
          pressure_mb: 1010.0,
          pressure_in: 29.83,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 77,
          cloud: 3,
          feelslike_c: -3.9,
          feelslike_f: 25.0,
          windchill_c: -3.9,
          windchill_f: 25.0,
          heatindex_c: -0.1,
          heatindex_f: 31.9,
          dewpoint_c: -3.7,
          dewpoint_f: 25.4,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 10.9,
          gust_kph: 17.5,
          uv: 1.0
        },
        {
          time_epoch: 1705302000,
          time: '2024-01-15 07:00',
          temp_c: -0.2,
          temp_f: 31.6,
          is_day: 0,
          condition: {
            text: 'Clear',
            icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
            code: 1000
          },
          wind_mph: 7.2,
          wind_kph: 11.5,
          wind_degree: 311,
          wind_dir: 'NW',
          pressure_mb: 1010.0,
          pressure_in: 29.83,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 79,
          cloud: 3,
          feelslike_c: -4.0,
          feelslike_f: 24.8,
          windchill_c: -4.0,
          windchill_f: 24.8,
          heatindex_c: -0.2,
          heatindex_f: 31.6,
          dewpoint_c: -3.4,
          dewpoint_f: 25.9,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 10.4,
          gust_kph: 16.7,
          uv: 1.0
        },
        {
          time_epoch: 1705305600,
          time: '2024-01-15 08:00',
          temp_c: -0.4,
          temp_f: 31.4,
          is_day: 0,
          condition: {
            text: 'Clear',
            icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
            code: 1000
          },
          wind_mph: 7.4,
          wind_kph: 11.9,
          wind_degree: 316,
          wind_dir: 'NW',
          pressure_mb: 1011.0,
          pressure_in: 29.84,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 72,
          cloud: 4,
          feelslike_c: -4.2,
          feelslike_f: 24.4,
          windchill_c: -4.2,
          windchill_f: 24.4,
          heatindex_c: -0.4,
          heatindex_f: 31.4,
          dewpoint_c: -4.8,
          dewpoint_f: 23.4,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 10.7,
          gust_kph: 17.2,
          uv: 1.0
        },
        {
          time_epoch: 1705309200,
          time: '2024-01-15 09:00',
          temp_c: -0.1,
          temp_f: 31.7,
          is_day: 1,
          condition: {
            text: 'Sunny',
            icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
            code: 1000
          },
          wind_mph: 7.8,
          wind_kph: 12.6,
          wind_degree: 318,
          wind_dir: 'NW',
          pressure_mb: 1011.0,
          pressure_in: 29.86,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 65,
          cloud: 4,
          feelslike_c: -4.1,
          feelslike_f: 24.6,
          windchill_c: -4.1,
          windchill_f: 24.6,
          heatindex_c: -0.2,
          heatindex_f: 31.7,
          dewpoint_c: -5.9,
          dewpoint_f: 21.3,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 10.9,
          gust_kph: 17.5,
          uv: 2.0
        },
        {
          time_epoch: 1705312800,
          time: '2024-01-15 10:00',
          temp_c: 0.5,
          temp_f: 32.9,
          is_day: 1,
          condition: {
            text: 'Sunny',
            icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
            code: 1000
          },
          wind_mph: 9.4,
          wind_kph: 15.1,
          wind_degree: 327,
          wind_dir: 'NNW',
          pressure_mb: 1012.0,
          pressure_in: 29.88,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 58,
          cloud: 2,
          feelslike_c: -3.8,
          feelslike_f: 25.1,
          windchill_c: -3.8,
          windchill_f: 25.1,
          heatindex_c: 0.5,
          heatindex_f: 32.9,
          dewpoint_c: -6.7,
          dewpoint_f: 20.0,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 12.3,
          gust_kph: 19.8,
          uv: 2.0
        },
        {
          time_epoch: 1705316400,
          time: '2024-01-15 11:00',
          temp_c: 1.1,
          temp_f: 34.0,
          is_day: 1,
          condition: {
            text: 'Sunny',
            icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
            code: 1000
          },
          wind_mph: 10.3,
          wind_kph: 16.6,
          wind_degree: 332,
          wind_dir: 'NNW',
          pressure_mb: 1013.0,
          pressure_in: 29.9,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 54,
          cloud: 2,
          feelslike_c: -3.3,
          feelslike_f: 26.1,
          windchill_c: -3.3,
          windchill_f: 26.1,
          heatindex_c: 1.1,
          heatindex_f: 34.0,
          dewpoint_c: -7.1,
          dewpoint_f: 19.2,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 13.1,
          gust_kph: 21.1,
          uv: 2.0
        },
        {
          time_epoch: 1705320000,
          time: '2024-01-15 12:00',
          temp_c: 1.7,
          temp_f: 35.1,
          is_day: 1,
          condition: {
            text: 'Sunny',
            icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
            code: 1000
          },
          wind_mph: 10.7,
          wind_kph: 17.3,
          wind_degree: 336,
          wind_dir: 'NNW',
          pressure_mb: 1013.0,
          pressure_in: 29.9,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 51,
          cloud: 3,
          feelslike_c: -2.7,
          feelslike_f: 27.2,
          windchill_c: -2.7,
          windchill_f: 27.2,
          heatindex_c: 1.7,
          heatindex_f: 35.1,
          dewpoint_c: -7.3,
          dewpoint_f: 18.8,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 13.5,
          gust_kph: 21.7,
          uv: 2.0
        },
        {
          time_epoch: 1705323600,
          time: '2024-01-15 13:00',
          temp_c: 2.1,
          temp_f: 35.8,
          is_day: 1,
          condition: {
            text: 'Sunny',
            icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
            code: 1000
          },
          wind_mph: 11.0,
          wind_kph: 17.6,
          wind_degree: 336,
          wind_dir: 'NNW',
          pressure_mb: 1013.0,
          pressure_in: 29.91,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 48,
          cloud: 4,
          feelslike_c: -2.2,
          feelslike_f: 28.0,
          windchill_c: -2.2,
          windchill_f: 28.0,
          heatindex_c: 2.1,
          heatindex_f: 35.8,
          dewpoint_c: -7.7,
          dewpoint_f: 18.1,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 13.8,
          gust_kph: 22.1,
          uv: 2.0
        },
        {
          time_epoch: 1705327200,
          time: '2024-01-15 14:00',
          temp_c: 2.2,
          temp_f: 36.0,
          is_day: 1,
          condition: {
            text: 'Sunny',
            icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
            code: 1000
          },
          wind_mph: 10.5,
          wind_kph: 16.9,
          wind_degree: 335,
          wind_dir: 'NNW',
          pressure_mb: 1013.0,
          pressure_in: 29.91,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 46,
          cloud: 0,
          feelslike_c: -2.0,
          feelslike_f: 28.4,
          windchill_c: -2.0,
          windchill_f: 28.4,
          heatindex_c: 2.2,
          heatindex_f: 36.0,
          dewpoint_c: -8.1,
          dewpoint_f: 17.4,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 13.4,
          gust_kph: 21.6,
          uv: 2.0
        },
        {
          time_epoch: 1705330800,
          time: '2024-01-15 15:00',
          temp_c: 2.0,
          temp_f: 35.6,
          is_day: 1,
          condition: {
            text: 'Sunny',
            icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
            code: 1000
          },
          wind_mph: 9.2,
          wind_kph: 14.8,
          wind_degree: 334,
          wind_dir: 'NNW',
          pressure_mb: 1013.0,
          pressure_in: 29.92,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 46,
          cloud: 4,
          feelslike_c: -1.9,
          feelslike_f: 28.6,
          windchill_c: -1.9,
          windchill_f: 28.6,
          heatindex_c: 2.0,
          heatindex_f: 35.6,
          dewpoint_c: -8.2,
          dewpoint_f: 17.2,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 12.1,
          gust_kph: 19.5,
          uv: 2.0
        },
        {
          time_epoch: 1705334400,
          time: '2024-01-15 16:00',
          temp_c: 1.3,
          temp_f: 34.3,
          is_day: 1,
          condition: {
            text: 'Sunny',
            icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
            code: 1000
          },
          wind_mph: 8.3,
          wind_kph: 13.3,
          wind_degree: 335,
          wind_dir: 'NNW',
          pressure_mb: 1014.0,
          pressure_in: 29.94,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 48,
          cloud: 3,
          feelslike_c: -2.5,
          feelslike_f: 27.5,
          windchill_c: -2.5,
          windchill_f: 27.5,
          heatindex_c: 1.3,
          heatindex_f: 34.3,
          dewpoint_c: -8.5,
          dewpoint_f: 16.8,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 11.8,
          gust_kph: 19.0,
          uv: 2.0
        },
        {
          time_epoch: 1705338000,
          time: '2024-01-15 17:00',
          temp_c: 0.7,
          temp_f: 33.2,
          is_day: 0,
          condition: {
            text: 'Clear',
            icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
            code: 1000
          },
          wind_mph: 7.4,
          wind_kph: 11.9,
          wind_degree: 333,
          wind_dir: 'NNW',
          pressure_mb: 1014.0,
          pressure_in: 29.96,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 49,
          cloud: 4,
          feelslike_c: -3.0,
          feelslike_f: 26.6,
          windchill_c: -3.0,
          windchill_f: 26.6,
          heatindex_c: 0.7,
          heatindex_f: 33.2,
          dewpoint_c: -8.8,
          dewpoint_f: 16.1,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 11.0,
          gust_kph: 17.6,
          uv: 1.0
        },
        {
          time_epoch: 1705341600,
          time: '2024-01-15 18:00',
          temp_c: 0.3,
          temp_f: 32.5,
          is_day: 0,
          condition: {
            text: 'Clear',
            icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
            code: 1000
          },
          wind_mph: 6.5,
          wind_kph: 10.4,
          wind_degree: 326,
          wind_dir: 'NNW',
          pressure_mb: 1015.0,
          pressure_in: 29.97,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 49,
          cloud: 1,
          feelslike_c: -3.1,
          feelslike_f: 26.4,
          windchill_c: -3.1,
          windchill_f: 26.4,
          heatindex_c: 0.3,
          heatindex_f: 32.5,
          dewpoint_c: -9.1,
          dewpoint_f: 15.5,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 9.8,
          gust_kph: 15.8,
          uv: 1.0
        },
        {
          time_epoch: 1705345200,
          time: '2024-01-15 19:00',
          temp_c: 0.0,
          temp_f: 32.0,
          is_day: 0,
          condition: {
            text: 'Clear',
            icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
            code: 1000
          },
          wind_mph: 6.0,
          wind_kph: 9.7,
          wind_degree: 325,
          wind_dir: 'NW',
          pressure_mb: 1016.0,
          pressure_in: 29.99,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 48,
          cloud: 3,
          feelslike_c: -3.2,
          feelslike_f: 26.2,
          windchill_c: -3.2,
          windchill_f: 26.2,
          heatindex_c: 0.0,
          heatindex_f: 32.0,
          dewpoint_c: -9.6,
          dewpoint_f: 14.8,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 9.1,
          gust_kph: 14.7,
          uv: 1.0
        },
        {
          time_epoch: 1705348800,
          time: '2024-01-15 20:00',
          temp_c: -0.2,
          temp_f: 31.7,
          is_day: 0,
          condition: {
            text: 'Clear',
            icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
            code: 1000
          },
          wind_mph: 5.4,
          wind_kph: 8.6,
          wind_degree: 321,
          wind_dir: 'NW',
          pressure_mb: 1016.0,
          pressure_in: 30.01,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 47,
          cloud: 7,
          feelslike_c: -3.2,
          feelslike_f: 26.3,
          windchill_c: -3.2,
          windchill_f: 26.3,
          heatindex_c: -0.2,
          heatindex_f: 31.7,
          dewpoint_c: -10.0,
          dewpoint_f: 14.0,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 8.1,
          gust_kph: 13.0,
          uv: 1.0
        },
        {
          time_epoch: 1705352400,
          time: '2024-01-15 21:00',
          temp_c: -0.3,
          temp_f: 31.4,
          is_day: 0,
          condition: {
            text: 'Clear',
            icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
            code: 1000
          },
          wind_mph: 4.9,
          wind_kph: 7.9,
          wind_degree: 312,
          wind_dir: 'NW',
          pressure_mb: 1017.0,
          pressure_in: 30.03,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 46,
          cloud: 16,
          feelslike_c: -3.1,
          feelslike_f: 26.4,
          windchill_c: -3.1,
          windchill_f: 26.4,
          heatindex_c: -0.3,
          heatindex_f: 31.4,
          dewpoint_c: -10.4,
          dewpoint_f: 13.3,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 7.3,
          gust_kph: 11.8,
          uv: 1.0
        },
        {
          time_epoch: 1705356000,
          time: '2024-01-15 22:00',
          temp_c: -0.4,
          temp_f: 31.2,
          is_day: 0,
          condition: {
            text: 'Overcast',
            icon: '//cdn.weatherapi.com/weather/64x64/night/122.png',
            code: 1009
          },
          wind_mph: 4.3,
          wind_kph: 6.8,
          wind_degree: 307,
          wind_dir: 'NW',
          pressure_mb: 1017.0,
          pressure_in: 30.04,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 46,
          cloud: 98,
          feelslike_c: -2.9,
          feelslike_f: 26.9,
          windchill_c: -2.9,
          windchill_f: 26.9,
          heatindex_c: -0.4,
          heatindex_f: 31.2,
          dewpoint_c: -10.6,
          dewpoint_f: 12.9,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 6.3,
          gust_kph: 10.1,
          uv: 1.0
        },
        {
          time_epoch: 1705359600,
          time: '2024-01-15 23:00',
          temp_c: -0.3,
          temp_f: 31.5,
          is_day: 0,
          condition: {
            text: 'Overcast',
            icon: '//cdn.weatherapi.com/weather/64x64/night/122.png',
            code: 1009
          },
          wind_mph: 3.8,
          wind_kph: 6.1,
          wind_degree: 304,
          wind_dir: 'NW',
          pressure_mb: 1017.0,
          pressure_in: 30.04,
          precip_mm: 0.0,
          precip_in: 0.0,
          snow_cm: 0.0,
          humidity: 44,
          cloud: 100,
          feelslike_c: -2.4,
          feelslike_f: 27.8,
          windchill_c: -2.4,
          windchill_f: 27.8,
          heatindex_c: -0.3,
          heatindex_f: 31.6,
          dewpoint_c: -10.9,
          dewpoint_f: 12.3,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 5.4,
          gust_kph: 8.7,
          uv: 1.0
        }
      ]
    }
  ]
}

export default async function getClima(latitud: string, longitude: string) {
  const key = process.env.NEXT_PUBLIC_API_KEY

  try {
    // const response = await fetch(
    //   `https://api.weatherapi.com/v1/forecast.json?key=${key}&q=${
    //     latitud || '40.71277'
    //   },${longitude || '-74.0059'}&lang=en&days=3&aqi=no&alerts=no`
    // )

    // const data = await response.json()

    // if (!data) {
    //   console.error('error api')
    //   return
    // }
    // return {
    //   current: data.current || currentEjem,
    //   location: data.location || locationEjem,
    //   forecast: data.forecast || forecastEjem
    // }
    return {
      current: currentEjem,
      location: locationEjem,
      forecast: forecastEjem
    }
  } catch (e) {
    console.error(e)
  }
}
